version: '2'

services:
  redis:
    container_name: redis_container
    image: redis:7
    ports:
      - '6379:6379'
    expose:
      - '6379'
    environment:
      TERM: xterm-256color
  db:
    image: postgres:14
    environment:
      TZ: America/Fortaleza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TERM: xterm-256color
    ports:
      - '5432:5432'
    expose:
      - '5432'

  web:
    build: .
    stdin_open: true
    tty: true
    entrypoint: config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    env_file:
      - ./.env.development
    volumes:
     - .:/home/app/web
    ports:
      - '3000:3000'

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    env_file:
      - ./.env.development
    volumes:
      - .:/home/app/web
