version: '1.0.0'

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379

  db:
    image: postgres:14
    environment:
      TZ: America/Fortaleza
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      TERM: xterm-256color
    ports:
      - '5432:5432'
    expose:
      - '5432'

  web:
    build: .
    stdin_open: true
    tty: true


