
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: app_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: app_test
  port: 5432

production:
  <<: *default
  database: postgres
  username: postgres
  password: <%= ENV["DOCKER_RAILS_DATABASE_PASSWORD"] %>
